// mksignet: build a test signet file from mockdiviner seeds.
//go:build janos_signtest

package main

import (
	"encoding/hex"
	"flag"
	"fmt"
	"os"

	"internal/runtime/janos_ed25519"
)

func main() {
	guildSeed := flag.String("guild", "guild", "guild seed label (right-padded to 32 bytes)")
	releaseSeed := flag.String("release", "release", "release seed label (right-padded to 32 bytes)")
	epoch := flag.Uint("epoch", 1, "release epoch")
	flag.Parse()

	guildBytes := padSeed(*guildSeed)
	releaseBytes := padSeed(*releaseSeed)

	guildPub, _ := janos_ed25519.SignForTest(guildBytes, nil)
	releasePub, _ := janos_ed25519.SignForTest(releaseBytes, nil)
	// Guild signs release_pubkey => parent_cert.
	_, parentCert := janos_ed25519.SignForTest(guildBytes, releasePub[:])

	guildLabelHex := hex.EncodeToString(bytesLabel(*guildSeed))
	releaseLabelHex := hex.EncodeToString(bytesLabel(*releaseSeed))
	fmt.Fprintf(os.Stderr, "guild_diviner_url:   mockdiviner://%s\n", guildLabelHex)
	fmt.Fprintf(os.Stderr, "release_diviner_url: mockdiviner://%s\n", releaseLabelHex)

	fmt.Printf("# generated by mksignet\n")
	fmt.Printf("guild_pubkey     = %s\n", hex.EncodeToString(guildPub[:]))
	fmt.Printf("guild_diviner    = mockdiviner://%s\n", guildLabelHex)
	fmt.Printf("release_pubkey   = %s\n", hex.EncodeToString(releasePub[:]))
	fmt.Printf("release_diviner  = mockdiviner://%s\n", releaseLabelHex)
	fmt.Printf("release_parent_cert = %s\n", hex.EncodeToString(parentCert[:]))
	fmt.Printf("release_epoch    = %d\n", *epoch)
}

func padSeed(s string) [32]byte {
	var out [32]byte
	copy(out[:], s)
	return out
}

func bytesLabel(s string) []byte {
	b := make([]byte, len(s))
	copy(b, s)
	return b
}
