// Copyright 2026 The Enigmaneering Authors.
// SPDX-License-Identifier: BSD-3-Clause
//
// JanOS: goroutine provenance.
//
// The identity of a running JanOS instance is a two-tuple:
//
//	(BinaryHash, InstanceID)
//
// BinaryHash is the SHA-256 self-attestation of the binary — the only
// identity that represents the codebase across every deployment target.
// (Hardware attestation proves the *location* of execution, but WASM
// can't do hardware attestation, so self-attestation is the minimum
// available across native, tamago, and browser targets alike.)
//
// InstanceID is a runtime-generated random identifier assigned once at
// schedinit and inherited by every goroutine. Two processes running
// the same binary have the same BinaryHash but different InstanceIDs;
// this lets a neural-network-style topology of same-binary peers keep
// each peer individually addressable even though they share code.
//
// Every g carries a gProvenance value copied — never referenced —
// from its creator at newproc1 time (see src/runtime/proc.go). Provenance
// is set on g0 during schedinit; user code sets the BinaryHash later via
// SetRootBinaryAttestation once it has computed the binary's digest with
// a target-appropriate method (reading /proc/self/exe, os.Executable(),
// fetching the running wasm module, or reading the tamago boot image).

package runtime

import "internal/runtime/atomic"

// gProvenance is the identity of the binary a goroutine is executing.
// It is copied — never referenced — into child goroutines, so it is
// safe to embed by value in g.
type gProvenance struct {
	// instanceID uniquely identifies this running JanOS instance.
	// Generated by janosInitInstanceID at schedinit and inherited
	// by every goroutine from that point forward.
	instanceID [16]byte
	// binaryHash is the SHA-256 self-attestation of the running binary.
	// Zero until SetRootBinaryAttestation is called during boot.
	binaryHash [32]byte
	// trustLevel records how the current identity was established.
	trustLevel TrustLevel
	// _ padding — keeps the struct 8-byte aligned regardless of GOARCH.
	_ [7]byte
}

// rootAttestSet guards SetRootBinaryAttestation against a second call.
// Zero == not yet attested; nonzero == attested. See also
// janosResetRootAttestForTest, which the runtime test harness uses to
// reset this between test cases; production callers never touch it.
var rootAttestSet atomic.Uint32

// janosInitInstanceID populates the current g's instance ID with 16
// random bytes. It is called from schedinit after randinit has finished
// and rand() is safe to call. Every subsequent goroutine inherits the
// value via newproc1's provenance copy.
//
//go:nosplit
func janosInitInstanceID() {
	gp := getg()
	hi := rand()
	lo := rand()
	for i := 0; i < 8; i++ {
		gp.provenance.instanceID[i] = byte(hi >> (8 * i))
		gp.provenance.instanceID[8+i] = byte(lo >> (8 * i))
	}
}

// janosSetGProvenance overwrites the provenance of the given g.
// Package-internal — reserved for the runtime's own boot path and
// future signed-boundary crossings in JanOS colonels. User code
// interacts with provenance only via SetRootBinaryAttestation
// (write, once) and CurrentProvenance (read).
//
//go:nosplit
func janosSetGProvenance(gp *g, p Provenance) {
	gp.provenance.instanceID = p.InstanceID
	gp.provenance.binaryHash = p.BinaryHash
	gp.provenance.trustLevel = p.TrustLevel
}

// Provenance is the identity of the code a goroutine is executing.
//
// InstanceID uniquely identifies this running JanOS instance. Two
// processes launched from the same binary have the same BinaryHash
// but different InstanceIDs.
//
// BinaryHash is the SHA-256 self-attestation of the running binary.
// It is zero until the JanOS boot code has computed the digest and
// called SetRootBinaryAttestation.
//
// TrustLevel records how strongly the identity has been established.
//
// The zero value describes an unattested goroutine (TrustLevel ==
// TrustNone), which is the state a JanOS binary boots in until
// self-attestation completes.
type Provenance struct {
	InstanceID [16]byte
	BinaryHash [32]byte
	TrustLevel TrustLevel
}

// TrustLevel records how strongly the current provenance has been verified.
type TrustLevel uint8

// Trust levels, in ascending order of strength.
const (
	// TrustNone: identity has not been established (zero value).
	TrustNone TrustLevel = iota
	// TrustSelfAttested: the binary hashed itself at boot and asserted
	// its own identity. The floor across every JanOS target — the only
	// trust level available in the browser (wasm) — and vulnerable to
	// a tampered runtime.
	TrustSelfAttested
	// TrustHardwareAttested: a TPM/SE has independently confirmed the
	// running binary's measurement matches an expected value.
	TrustHardwareAttested
	// TrustColonelAttested: a JanOS colonel has verified this binary
	// at load time against a chain rooted in silicon.
	TrustColonelAttested
)

// String returns a human-readable name for the trust level.
func (t TrustLevel) String() string {
	switch t {
	case TrustNone:
		return "none"
	case TrustSelfAttested:
		return "self-attested"
	case TrustHardwareAttested:
		return "hardware-attested"
	case TrustColonelAttested:
		return "colonel-attested"
	default:
		return "unknown"
	}
}

// CurrentProvenance returns the provenance of the currently executing
// goroutine.
//
// It reads directly off the g descriptor — no allocation, no syscall,
// no lock. Safe to call in hot paths. The returned value is a
// snapshot; provenance is fixed for the lifetime of a goroutine, so
// callers do not need to worry about the value changing under them.
//
//go:nosplit
func CurrentProvenance() Provenance {
	gp := getg()
	return Provenance{
		InstanceID: gp.provenance.instanceID,
		BinaryHash: gp.provenance.binaryHash,
		TrustLevel: gp.provenance.trustLevel,
	}
}

// SetRootBinaryAttestation records the SHA-256 self-attestation of the
// running binary against the current goroutine's provenance. It must
// be called exactly once per process, before any worker goroutines
// have been spawned — typically from an init() function in the JanOS
// bootstrap package that computes the hash with a target-appropriate
// method.
//
// Level must be TrustSelfAttested or stronger. Passing TrustNone is a
// programming error (there is nothing to attest).
//
// A second call throws. All goroutines created after this call
// inherit the attested identity; the InstanceID assigned at schedinit
// is preserved.
func SetRootBinaryAttestation(hash [32]byte, level TrustLevel) {
	if level == TrustNone {
		throw("runtime.SetRootBinaryAttestation: level must be at least TrustSelfAttested")
	}
	if !rootAttestSet.CompareAndSwap(0, 1) {
		throw("runtime.SetRootBinaryAttestation called more than once")
	}
	gp := getg()
	gp.provenance.binaryHash = hash
	gp.provenance.trustLevel = level
}
