// Copyright The Enigmaneering Guild. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// JanOS: goroutine provenance.
//
// The identity of a running JanOS instance is a two-tuple:
//
//	(BinaryHash, InstanceID)
//
// BinaryHash is the SHA-256 self-attestation of the binary — the only
// identity that represents the codebase across every deployment target.
// (Hardware attestation proves the *location* of execution, but WASM
// can't do hardware attestation, so self-attestation is the minimum
// available across native, tamago, and browser targets alike.)
//
// InstanceID is a runtime-generated random identifier assigned once at
// schedinit and inherited by every goroutine.  Two processes running
// the same binary have the same BinaryHash but different InstanceIDs;
// this lets a neural-network-style topology of same-binary peers keep
// each peer individually addressable even though they share code.
//
// Both fields are set implicitly by the runtime at schedinit — see
// janos_selfhash.go for the binary hash reader and janosInitInstanceID
// below for the instance ID generator.  User code interacts with
// provenance only through the read-only CurrentProvenance accessor.
// Every g carries a gProvenance value copied — never referenced —
// from its creator at newproc1 time (see src/runtime/proc.go).

package runtime

// gProvenance is the identity of the binary a goroutine is executing.
// It is copied — never referenced — into child goroutines, so it is
// safe to embed by value in g.
type gProvenance struct {
	// instanceID uniquely identifies this running JanOS instance.
	// Generated by janosInitInstanceID at schedinit and inherited
	// by every goroutine from that point forward.
	instanceID [16]byte
	// binaryHash is the SHA-256 self-attestation of the running binary.
	// Set by janosInitBinaryHash at schedinit on platforms with a
	// working self-hash reader; zero on stub platforms.
	binaryHash [32]byte
	// trustLevel records how the current identity was established.
	trustLevel TrustLevel
	// _ padding — keeps the struct 8-byte aligned regardless of GOARCH.
	_ [7]byte
}

// janosInitInstanceID populates the current g's instance ID with 16
// random bytes.  It is called from schedinit after randinit has
// finished and rand() is safe to call.  Every subsequent goroutine
// inherits the value via newproc1's provenance copy.
//
//go:nosplit
func janosInitInstanceID() {
	gp := getg()
	hi := rand()
	lo := rand()
	for i := 0; i < 8; i++ {
		gp.provenance.instanceID[i] = byte(hi >> (8 * i))
		gp.provenance.instanceID[8+i] = byte(lo >> (8 * i))
	}
}

// janosSetGProvenance overwrites the provenance of the given g.
// Package-internal — reserved for future signed-boundary crossings in
// JanOS colonels.  User code never sets provenance directly.
//
//go:nosplit
func janosSetGProvenance(gp *g, p Provenance) {
	gp.provenance.instanceID = p.InstanceID
	gp.provenance.binaryHash = p.BinaryHash
	gp.provenance.trustLevel = p.TrustLevel
}

// Provenance is the identity of the code a goroutine is executing.
//
// InstanceID uniquely identifies this running JanOS instance.  Two
// processes launched from the same binary have the same BinaryHash
// but different InstanceIDs.
//
// BinaryHash is the SHA-256 self-attestation of the running binary.
// It is populated automatically by the runtime at schedinit on
// platforms with a native self-hash reader; where no reader is
// implemented yet, it is the zero value and TrustLevel is TrustNone.
//
// TrustLevel records how strongly the identity has been established.
//
// The zero value describes an unattested goroutine (TrustLevel ==
// TrustNone), which occurs on platforms without a self-hash reader.
type Provenance struct {
	InstanceID [16]byte
	BinaryHash [32]byte
	TrustLevel TrustLevel
}

// TrustLevel records how strongly the current provenance has been verified.
type TrustLevel uint8

// Trust levels, in ascending order of strength.
const (
	// TrustNone: identity has not been established (zero value).
	TrustNone TrustLevel = iota
	// TrustSelfAttested: the binary hashed itself at boot and asserted
	// its own identity.  The floor across every JanOS target — the only
	// trust level available in the browser (wasm) — and vulnerable to
	// a tampered runtime.
	TrustSelfAttested
	// TrustHardwareAttested: a TPM/SE has independently confirmed the
	// running binary's measurement matches an expected value.
	TrustHardwareAttested
	// TrustColonelAttested: a JanOS colonel has verified this binary
	// at load time against a chain rooted in silicon.
	TrustColonelAttested
)

// String returns a human-readable name for the trust level.
func (t TrustLevel) String() string {
	switch t {
	case TrustNone:
		return "none"
	case TrustSelfAttested:
		return "self-attested"
	case TrustHardwareAttested:
		return "hardware-attested"
	case TrustColonelAttested:
		return "colonel-attested"
	default:
		return "unknown"
	}
}

// CurrentProvenance returns the provenance of the currently executing
// goroutine.
//
// It reads directly off the g descriptor — no allocation, no syscall,
// no lock.  Safe to call in hot paths.  The returned value is a
// snapshot; provenance is fixed for the lifetime of a goroutine, so
// callers do not need to worry about the value changing under them.
//
//go:nosplit
func CurrentProvenance() Provenance {
	gp := getg()
	return Provenance{
		InstanceID: gp.provenance.instanceID,
		BinaryHash: gp.provenance.binaryHash,
		TrustLevel: gp.provenance.trustLevel,
	}
}
