// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package copyright

import (
	"bytes"
	"internal/testenv"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var copyright = []byte("Copyright")

var permitted = [][]byte{
	[]byte("// Code generated by "),
	[]byte("// Code generated from "),
	[]byte("// Created by cgo -cdefs"),
	[]byte("// DO NOT EDIT\n// generated by:"),
	[]byte("// Empty assembly file"),
	[]byte("// Generated using cgo"),
	[]byte("// Original source:\n//\thttp://www.zorinaq.com/papers/md5-amd64.html"), // public domain crypto/md5
	[]byte("// created by cgo -cdefs"),
	[]byte("// go run mkasm.go"),
	[]byte("// mkerrors"),
	[]byte("// mksys"),
	[]byte("// run\n// Code generated by"), // cmd/compile/internal/test/constFold_test.go
	[]byte("//go:build !nethttpomithttp2"), // hack to pacify h2_bundle, which drops copyright header
}

// isJanosAuthored reports whether path is a JanOS-authored file that
// deliberately does not carry a copyright header.  Per the convention
// documented in colonel/additions.md, JanOS-original files start
// directly with their doc comment / build tag / package declaration;
// only files with a pre-existing upstream Go / Inferno header get an
// appended "Copyright The Enigmaneering Guild" line.  The pre-existing
// files are covered by TestCopyright's normal check (they still contain
// "Copyright"); the JanOS-original files need this skip.
func isJanosAuthored(path string) bool {
	// Files whose base name starts with "janos_" or "janos-" are ours.
	base := filepath.Base(path)
	if strings.HasPrefix(base, "janos_") || strings.HasPrefix(base, "janos-") {
		return true
	}
	// Files in JanOS-authored subtrees.
	// Use forward slashes for portable matching.
	slashPath := filepath.ToSlash(path)
	janosDirs := []string{
		"/src/cmd/janos/",
		"/src/internal/runtime/janos_hash/",
		"/src/quantum/",
	}
	for _, d := range janosDirs {
		if strings.Contains(slashPath, d) {
			return true
		}
	}
	// Files in cmd/link/internal/ld/ whose base starts with "janos_"
	// are covered by the base check above; other files there keep
	// their Inferno-lineage headers.
	return false
}

func TestCopyright(t *testing.T) {
	testenv.MustHaveSource(t)
	buf := make([]byte, 2048)
	filepath.WalkDir(filepath.Join(testenv.GOROOT(t), "src"), func(path string, d fs.DirEntry, err error) error {
		if d.IsDir() && (d.Name() == "testdata" || d.Name() == "vendor") {
			return filepath.SkipDir
		}
		switch filepath.Ext(d.Name()) {
		default:
			return nil
		case ".s", ".go":
			// check
		}
		// JanOS convention: JanOS-original files carry no copyright
		// header.  Modified upstream Go/tamago/Inferno files DO carry
		// an appended Enigmaneering Guild line and are covered by the
		// normal Copyright substring check below.
		if isJanosAuthored(path) {
			return nil
		}

		f, err := os.Open(path)
		if err != nil {
			t.Error(err)
			return nil
		}
		defer f.Close()
		n, err := f.Read(buf)
		if err != nil && err != io.EOF {
			t.Error(err)
			return nil
		}
		b := buf[:n]
		if bytes.Contains(b, copyright) {
			return nil
		}
		for _, ok := range permitted {
			if bytes.HasPrefix(b, ok) {
				return nil
			}
		}
		t.Logf("%.100s %s", b, path)
		t.Errorf("%s: missing copyright notice", path)
		return nil
	})
}
