// mksignet: build a test signet file from mockdiviner seeds.
//
// Produces the file format cmd/janos/signet expects, using
// deterministically-derived ECDSA P-256 keypairs.  Used by cmd/link
// end-to-end tests that need a signet without a real KMS.  Only
// builds with -tags janos_signtest.
//
//go:build janos_signtest

package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"math/big"
	"os"
)

func main() {
	guildSeed := flag.String("guild", "guild", "guild seed label (right-padded to 32 bytes)")
	releaseSeed := flag.String("release", "release", "release seed label (right-padded to 32 bytes)")
	epoch := flag.Uint("epoch", 1, "release epoch")
	flag.Parse()

	guildBytes := padSeed(*guildSeed)
	releaseBytes := padSeed(*releaseSeed)

	guildPriv, guildPub := keyFromSeed(guildBytes)
	_, releasePub := keyFromSeed(releaseBytes)

	// Guild signs SHA-256(release_pubkey) → parent_cert.
	digest := sha256.Sum256(releasePub[:])
	r, s, err := ecdsa.Sign(rand.Reader, guildPriv, digest[:])
	if err != nil {
		fmt.Fprintf(os.Stderr, "mksignet: guild sign: %v\n", err)
		os.Exit(1)
	}
	var parentCert [64]byte
	rBytes := r.Bytes()
	sBytes := s.Bytes()
	copy(parentCert[32-len(rBytes):32], rBytes)
	copy(parentCert[64-len(sBytes):64], sBytes)

	guildLabelHex := hex.EncodeToString(bytesLabel(*guildSeed))
	releaseLabelHex := hex.EncodeToString(bytesLabel(*releaseSeed))
	fmt.Fprintf(os.Stderr, "guild_diviner_url:   mockdiviner://%s\n", guildLabelHex)
	fmt.Fprintf(os.Stderr, "release_diviner_url: mockdiviner://%s\n", releaseLabelHex)

	fmt.Printf("# generated by mksignet (ECDSA P-256)\n")
	fmt.Printf("guild_pubkey     = %s\n", hex.EncodeToString(guildPub[:]))
	fmt.Printf("guild_diviner    = mockdiviner://%s\n", guildLabelHex)
	fmt.Printf("release_pubkey   = %s\n", hex.EncodeToString(releasePub[:]))
	fmt.Printf("release_diviner  = mockdiviner://%s\n", releaseLabelHex)
	fmt.Printf("release_parent_cert = %s\n", hex.EncodeToString(parentCert[:]))
	fmt.Printf("release_epoch    = %d\n", *epoch)
}

// keyFromSeed derives a deterministic P-256 keypair from a 32-byte
// seed.  Domain-separated so the same seed used for other purposes
// won't collide.  Matches the derivation cmd/janos/diviner/
// mockdiviner uses so a seed-derived pubkey here equals the pubkey
// the mockdiviner URL would report for the same seed.
func keyFromSeed(seed [32]byte) (*ecdsa.PrivateKey, [64]byte) {
	var dSeed [len("mockdiviner-key:") + 32]byte
	copy(dSeed[:len("mockdiviner-key:")], "mockdiviner-key:")
	copy(dSeed[len("mockdiviner-key:"):], seed[:])
	dHash := sha256.Sum256(dSeed[:])

	curve := elliptic.P256()
	d := new(big.Int).SetBytes(dHash[:])
	d.Mod(d, curve.Params().N)
	if d.Sign() == 0 {
		d.SetInt64(1)
	}
	priv := &ecdsa.PrivateKey{}
	priv.PublicKey.Curve = curve
	priv.D = d
	priv.PublicKey.X, priv.PublicKey.Y = curve.ScalarBaseMult(d.Bytes())

	var pub [64]byte
	xBytes := priv.PublicKey.X.Bytes()
	yBytes := priv.PublicKey.Y.Bytes()
	copy(pub[32-len(xBytes):32], xBytes)
	copy(pub[64-len(yBytes):64], yBytes)
	return priv, pub
}

func padSeed(s string) [32]byte {
	var out [32]byte
	copy(out[:], s)
	return out
}

func bytesLabel(s string) []byte {
	b := make([]byte, len(s))
	copy(b, s)
	return b
}
